# Generated by Django 3.1.2 on 2020-11-15 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alllisting_bid_closedbid_comment_listing_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='closedbid',
            old_name='listingid',
            new_name='closebid_listingid',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='price',
            new_name='startingBid',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='listingid',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='listingid',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='listingid',
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_listingid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_listingid', to='auctions.listing'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_listingid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_listingid', to='auctions.listing'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='watchlist_listingid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_listingid', to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='listing',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_id', to='auctions.category'),
        ),
    ]
