# Generated by Django 3.1.2 on 2020-11-15 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201115_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='closedbid',
            old_name='closebid_listingid',
            new_name='closedbid_listingid',
        ),
    ]
