# Generated by Django 3.1.2 on 2020-11-15 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201115_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alllisting',
            name='listingid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Alllistingid', to='auctions.listing'),
        ),
    ]
