# Generated by Django 3.1.2 on 2020-11-26 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20201124_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_listingid', to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_listingid',
            field=models.IntegerField(default=False),
            preserve_default=False,
        ),
    ]
