# Generated by Django 3.1.2 on 2020-11-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20201128_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_listingid',
            field=models.IntegerField(),
        ),
    ]
