# Generated by Django 3.1.2 on 2020-11-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20201128_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alllisting',
            old_name='listingid',
            new_name='listing',
        ),
        migrations.AddField(
            model_name='alllisting',
            name='Alllisting_listingid',
            field=models.IntegerField(null=True),
        ),
    ]
