# Generated by Django 3.1.2 on 2020-11-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20201128_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alllisting',
            name='Alllisting_listingid',
            field=models.IntegerField(default=False),
            preserve_default=False,
        ),
    ]
