# Generated by Django 3.1.2 on 2020-11-29 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20201128_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alllisting',
            name='listing',
        ),
    ]
